// rock-paper-scissors/vue/src/App.vue
<script setup lang="ts">
import HandIcon from './components/HandIcon.vue';
import RockIcon from './components/RockIcon.vue';
import ScissorIcon from './components/ScissorIcon.vue';
</script>

<template>
  <main>
    <header>
      <h1>Rock Paper Scissors</h1>
      <div>
        <p>Score</p>
        <p class="score"></p>
      </div>
    </header>
    <section>
      <HandIcon />
      <RockIcon />
      <ScissorIcon />
    </section>
  </main>
</template>

<style scoped>
header {
  border: 1px solid gray;
  border-radius: 1rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.5rem;

  & h1 {
    padding: 0.5rem;
  }

  & div {
    display: grid;
    justify-content: center;
    align-items: center;
    margin: 0.5rem;
    padding: 0.5rem;
  }
}
</style>

// rock-paper-scissors/react/src/App.tsx
import './App.css';
import HandIcon from './components/HandIcon';
import RockIcon from './components/RockIcon';
import ScissorIcon from './components/ScissorIcon';

export default function App() {
  return (
    <main>
      <header>
        <h1>Rock Paper Scissors</h1>
        <div>
          <p>Score</p>
          <p className="score"></p>
        </div>
      </header>
      <section>
        <HandIcon />
        <RockIcon />
        <ScissorIcon />
      </section>
    </main>
  );
}
